### ISSUE TITLE
SIGTERM Error during videomme and mlvu evaluation

### ISSUE THREAD

**Issue by MYMY-young** [EvolvingLMMs-Lab/lmms-eval#663]
Thank you for sharing such a great codebase.

I ran the following command:

accelerate launch --num_processes=4 --main_process_port=12345 -m lmms_eval \
  --model qwen2_vl \
  --model_args pretrained=my_model,device_map=cuda \
  --tasks videomme \
  --batch_size 1 \
  --log_samples \
  --log_samples_suffix qwen2_vl_dedug_vinoground \
  --output_path ./logs_videomme
However, I encountered the following error:

W0504 08:39:36.777000 2950364 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 2950432 closing signal SIGTERM

I am using 4 A6000 GPUs, and there was sufficient GPU memory available at the time of execution.
Interestingly, this issue only occurred on videomme and mlvu tasks.
When I ran other tasks such as mvbench, the evaluation completed successfully without any issues.

Could you help identify the possible cause?

**Comment by yogkul2000** [comment]
Did face similar issue, solved by increasing RAM to 500G/using only 2 GPUs

**Comment by MYMY-young** [comment]
Thanks for sharing your experience. I actually tried increasing the RAM to 500G, but unfortunately, the server shut down completely during execution. Still, I appreciate the suggestion!

**Comment by natwille1** [comment]
@MYMY-young  how did you install `lmms-eval`? I'm currently getting this error when running the command specified in the docs:

2025-05-08 11:21:47.916 | ERROR    | __main__:cli_evaluate:348 - Error during evaluation: Model plm not found in available models.. Please set `--verbosity=DEBUG` to get more information.

I installed lmms-eval using: `pip install lmms-eval` so should be up to date..

**Comment by Clementine24** [comment]
Has this issue been resolved? I'm still encountering this error on mvbench.

**Comment by Luodian** [comment]
Closing - looks like this was resolved. Feel free to reopen if you're still seeing issues\!
